# Generated by Django 6.0.1 on 2026-01-07 17:39

import django.core.validators
import films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='Оригинальное название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность (мин)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=films.models.film_poster_path, verbose_name='Постер')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('director', models.CharField(max_length=200, verbose_name='Режиссер')),
                ('genre', models.CharField(choices=[('action', 'Боевик'), ('comedy', 'Комедия'), ('drama', 'Драма'), ('horror', 'Ужасы'), ('sci_fi', 'Научная фантастика'), ('romance', 'Мелодрама'), ('thriller', 'Триллер'), ('documentary', 'Документальный'), ('animation', 'Анимация'), ('fantasy', 'Фэнтези')], max_length=50, verbose_name='Жанр')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг фильма')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilmEmotionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Интенсивность (1-10)')),
                ('description', models.TextField(blank=True, verbose_name='Описание воздействия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
            ],
            options={
                'verbose_name': 'Оценка эмоции фильма',
                'verbose_name_plural': 'Оценки эмоций фильмов',
                'ordering': ['-intensity'],
            },
        ),
    ]
