# Generated by Django 6.0.1 on 2026-01-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0001_initial'),
        ('films', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_created', to='users.userprofile', verbose_name='Добавил'),
        ),
        migrations.AddField(
            model_name='filmemotionrating',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_ratings', to='emotions.emotion', verbose_name='Эмоция'),
        ),
        migrations.AddField(
            model_name='filmemotionrating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_ratings', to='films.film', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='filmemotionrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to='users.userprofile', verbose_name='Оценил'),
        ),
        migrations.AddField(
            model_name='film',
            name='emotions',
            field=models.ManyToManyField(related_name='films', through='films.FilmEmotionRating', to='emotions.emotion', verbose_name='Эмоции'),
        ),
        migrations.AlterUniqueTogether(
            name='filmemotionrating',
            unique_together={('film', 'emotion')},
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['year'], name='films_film_year_30d277_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['rating'], name='films_film_rating_eacfff_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['genre'], name='films_film_genre_00aeeb_idx'),
        ),
    ]
