# Generated by Django 6.0.1 on 2026-01-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0001_initial'),
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('notification_frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=20, verbose_name='Частота уведомлений')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram ID')),
                ('search_history', models.JSONField(blank=True, default=list, verbose_name='История поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('favorite_films', models.ManyToManyField(blank=True, related_name='favorited_by', to='films.film', verbose_name='Любимые фильмы')),
                ('preferred_emotions', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='emotions.emotion', verbose_name='Предпочитаемые эмоции')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
