# Generated by Django 6.0.1 on 2026-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название эмоции"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание эмоционального состояния"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF6B6B", "Красный - страсть/гнев"),
                            ("#4ECDC4", "Бирюзовый - спокойствие"),
                            ("#FFD166", "Желтый - радость"),
                            ("#06D6A0", "Зеленый - гармония"),
                            ("#118AB2", "Синий - грусть"),
                            ("#EF476F", "Розовый - любовь"),
                            ("#073B4C", "Темно-синий - напряжение"),
                            ("#7209B7", "Фиолетовый - мистика"),
                        ],
                        default="#FF6B6B",
                        max_length=7,
                        verbose_name="Цвет для визуализации",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Название иконки (FontAwesome)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Эмоция",
                "verbose_name_plural": "Эмоции",
                "ordering": ["name"],
            },
        ),
    ]
